env:
  domain_name: "walker"
  task_name: "walk"
  render_mode: "human"  # Change to null or "rgb_array" for faster training

training:
  total_timesteps: 10000
  log_interval: 4
  verbose: 1

wandb:
  project: "TD-MPC2-Reproduce"
  entity: null
